### ISSUE TITLE
Update package to include most recent merges of PR

### ISSUE THREAD

**Issue by travisjwalter** [m4ce/crowd-api-python#17]
Hi Matteo,

Regarding our email, this is the issue I've created to see if you would be willing to update the package that is on PyPi to the most recent version.

Thanks!
Travis Walter

**Comment by m4ce** [comment]
Hi Travis,

sorry about the delay - package is published, see https://pypi.org/manage/project/crowd-api/releases/.

Should probably put a CI for this - you never have time for this stuff..
